### ISSUE TITLE
Projects using CabloyJS

### ISSUE THREAD

**Issue by zhennann** [zhennann/cabloy#12]
If you can share about your project, please do comment and let us all know🙏
如果方便的话，请将您的项目信息与大家分享、交流🙏

**Comment by zhennann** [comment]
## Blog / 博客

- [暮风洗月](https://zhennann.com)

## Technical Documentations / 技术文档

- [CabloyJS English](https://cabloy.com/index.html)
- [CabloyJS 中文](https://cabloy.com/zh-cn/index.html)

##  Community / 社区

- [Community English](https://community.cabloy.com/index.html)
- [Community 中文](https://community.cabloy.com/zh-cn/index.html)

## Store / 商店

- [Cabloy Store(English)](https://store.cabloy.com/index.html)
- [Cabloy商店(中文)](https://store.cabloy.com/zh-cn/index.html)

**Comment by superiums** [comment]
# 游仙区农民工服务信息系统

采用cabloy 3.0
- 形式：微信小程序
- 查看方式：微信搜索：游仙区农民工服务中心
- 主要功能：实名档案，数据整理，数据分析，求职招聘，信息发布，批量导入导出，重复数据处理等。
