### ISSUE TITLE
npm run dev:front启动报错

### ISSUE THREAD

**Issue by lizhongzhen11** [zhennann/cabloy#13]
作者你好，报错如下：
UnhandledSchemeError: Reading from "C:Projectcabloy-demo
ode_modulesegg-born-front__runtimemodulesa-basedistront.js" is not handled by plugins (Unhandled scheme).
Webpack supports "data:" and "file:" URIs by default.

You may need an additional plugin to handle "c:" URIs.

想问下这个该怎么解决？

**Comment by zhennann** [comment]
可否提供运行环境：操作系统，node版本，更详细的报错信息（截图就好）
是按照“快速开始”创建的项目，运行就报错吗？还是做了某些变更（操作）之后报错？

**Comment by zhennann** [comment]
有一个与windows不兼容的bug，已经修复。请更新至cabloy@4.0.34-alpha.0试试

**Comment by lizhongzhen11** [comment]
作者辛苦了，我待会试下

**Comment by lizhongzhen11** [comment]
谢谢作者，启动OK了！
