### ISSUE TITLE
考虑 AOP ，是不是可以考虑 nest.js  和 midwayjs 这样的框架。

### ISSUE THREAD

**Issue by zuohuadong** [zhennann/cabloy#15]
另外，工作流引擎是否可以独立使用。

**Comment by zhennann** [comment]
纯技术框架往往会纠结于用TS还是JS。但真正做业务，面对复杂的业务需求，能提高开发效率以及用户体验的往往是整个架构的设计理念与风格。
nest和midway把大部分精力都放在如何完美支持TS上，缺乏业务层面的基建，并不利于业务的快速开发。
单从github上面的代码提交而言，nest和midway的commits许多都是与类型相关的修复；而cabloy的commits大多都是与业务相关的基建特性

**Comment by zhennann** [comment]
工作流引擎除了流程本身的逻辑规则外，还需要许多周边基建作为支撑，比如：角色（组织）与人员、表单渲染、表单字段权限、定时任务、消息推送，等等。而Cabloy恰恰提供了这些丰富的基建特性，从而可以使工作流引擎达到开箱即用的效果，同时又具备灵活的可定制性、扩展性
