### ISSUE TITLE
CMS主题中图片位置优化

### ISSUE THREAD

**Issue by zhennann** [zhennann/cabloy#16]
<img width="475" alt="issue-cms" src="https://user-images.githubusercontent.com/24246985/122053517-680b3000-ce19-11eb-95f0-78a094318c47.png">

链接：https://community.cabloy.com/zh-cn/index.html

在mobile端会出现以下两个问题：

* 问题1.  图片有时会顶出容器
* 问题2. 图片下方左侧的文字没有补充右侧的空白区域。在pc端由于足够宽，所以效果不明显，在mobile端效果明显

* 延伸: 内置的其他主题应该也存在类似的问题，需要一并修改
    * cms-themeaws
    * cms-themeblog
    * cms-themecommunity
    * cms-themedocs

**Comment by ehitco** [comment]
hi, i want to try,  fix it will be my pleasure .

**Comment by zhennann** [comment]
welcome

**Comment by zhennann** [comment]
![1](https://user-images.githubusercontent.com/24246985/122151974-14d5c380-ce93-11eb-8ae9-fb242e542269.png)

1. 图片还是放在标题的右侧好看
2. 图片下方还是空白，文字没有向右延伸填充

**Comment by ehitco** [comment]
已更新图文混排样式

**Comment by zhennann** [comment]
#19 nice work, thanks
