### ISSUE TITLE
建议将命令行工具，脚手架相关代码单独建一个代码库。

### ISSUE THREAD

**Issue by ehitco** [zhennann/cabloy#17]
如题

**Comment by zhennann** [comment]
这样做的收益是什么？

**Comment by ehitco** [comment]
牵强一点说为了，职责单一，代码可读性吧，  源码库中的package 目录，是否应该仅作为 eggborn 的核心源码目录更好？更利于读者理解 eggborn。  vue的 vue-cli,  react 的 create-react-app 似乎都是单独的代码库。 想法不一定对，供参考。

**Comment by zhennann** [comment]
放在一个仓库，一方面，当修改代码时有现成的场景可以调试测试，另一方面，也便于在统一的位置接受社区PR
