### ISSUE TITLE
关于框架的几点疑惑

### ISSUE THREAD

**Issue by hscspring** [zhennann/cabloy#2]
作为一名算法准备上手做一款应用，有幸找到这款框架，无论从理念还是使用都非常喜欢，看了文档还是有一些疑问（纯新手），主要是结合自己应用方面的，希望能解答下，非常感激。

## 背景

要做的应用是给用户提供一个上传视频的接口，然后主要提供视频存储（包括查询、删除等）、视频分析（包括视频截图、人脸检测、人脸识别、情绪甄别等一系列服务）。

## 问题

1. 整个服务要分开写成多个 module 还是全部放在一个 module 里面？
2. 如果有多个 module 是怎么同时和前后端交互的？我试了一下（用 Tom 账号）两个模块（test-cook 和 test-todo）的内容会在一起出现，也就是说模块之间完全独立的，那彼此之间如果有数据交互要如何操作（比如上传的视频给分析接口）。不过新注册的或者用 demo001 的账户就只有 test-todo 模块的，但是登陆后 “新建” 功能都没定义。所以这里有点迷糊，一下子不知道该怎么上手了。

问题比较小白，主要是不知道第一步该怎么开始自己的项目，非常感谢。

**Comment by zhennann** [comment]
系统采用`schema`对表单字段进行定义，从而实现表单自动渲染和数据验证，所以在模块`test-todo`中看不到前端页面

你可以在读完模块`test-todo`后端代码之后，再读模块`a-cms`，就会更清晰了。

欢迎继续交流

**Comment by hscspring** [comment]
非常感谢答复。
我可能基础知识差的比较多，有一些 Gap，不过真心喜欢这个框架，感觉很有潜力。
我先按你讲的试试，如果有问题会再提 Issue 的，再次谢谢。

**Comment by zhennann** [comment]
👌

**Comment by hscspring** [comment]
你好，抱歉又要麻烦一下，又有几个问题……

## test-todo 项目的问题

1. 这个是 model 文件下的 `todo.js`，

```
module.exports = app => {
  class Todo extends app.meta.Model {
    constructor(ctx) {
      super(ctx, { table: 'testTodo', options: { disableDeleted: false } });
    }
  }
  return Todo;
};
```

这段代码不是很懂，我看了 eggjs 的文档也没发现这个。。。

2. `meta.js` 具体是怎么运用的，一直没看出来……
3.  `version.js` 我看到有个对数据库创建表的操作，我猜想应该是初始化时运行。我的问题是，这些操作是怎么和界面上的交互关联起来，比如有 100 个新注册用户，他们都创建了自己的列表，这些交互在哪里，以及数据是怎么进入数据库的，细节不是特别明白……

## cms 项目

1. 我看 cms 登陆后只能看到文章的相关操作（菜单和todo的都没了），不知道这个权限怎么操作的
2. cms 用到了和 hexo 类似的操作，那 `egg-born-module-cms-themeblog` 这个包的作用是不是就只是主题作用了
3. 注册了新用户后，没有创建文章的权限，但是好像没有看到注册或用户的操作代码，不知道这个是怎么弄



我也看了文档，还不是特别理解，东西太多也不知道该从哪儿看起。感觉都是一个一个点，没有连到一起，知道个大概但就是写不出来😅

我之前写过简单的前后端，就是没有数据库，没有用户系统那种，前端发一个 post 请求，后端收到请求直接给结果那种。当时前端用 create-react-app 写的。现在这个加了数据库和用户功能感觉复杂了好多倍……

**Comment by zhennann** [comment]
## test-todo 项目的问题

1. model是EggBorn实现的概念，主要是简化数据表的操作，并且内置支持`instance`和`deleted`软删除的功能。

`todo.js`就是声明了一个model类，标明用的哪个数据表，是否`禁用软删除`功能。

所有定义的model类文件都在main.js中引用，EggBorn会自动注入到后端服务中，直接使用

2. meta.js是元配置文件，其他不同的模块会更加自己的需要从中间获取配置

meta.js中的配置规则，是由不同的模块定义的

meta.js文件也是在main.js中引用

3. EggBorn模块通过version.js控制数据的版本变更。方便不同版本无缝升级。一般而言，数据表初始化后，在服务实际的运行中都不再创建新的数据表。 比如新注册用户只是在`用户表`中添加记录

## cms项目

1. 模块`todo`是演示用的，在cms中没有安装，所以看不到

2. 在模块`a-cms`的version.js中预置了两个角色`cms-writer`、`cms-publisher`，分别赋予文章的撰写和发布权限。`root`用户属于这两个角色，所以可以撰写文章。新注册的用户属于`registered`角色，所以没有撰写文章的权限。对于一般的blog而言，普通用户只能发表评论，不允许撰写文章。

`a-cms`的version.js只是预置了最常见的角色权限模型，这些都可以定制

3. 注册是模块`a-authsimple`实现的功能

## 建议

建议阅读文档顺序： EggJS -> EggBornJS -> CabloyJS 

这三个框架的概念都有延续性，比如EggJS中的概念，EggBornJS中为了避免繁琐就不会重复写。

此外，EggBornJS为了模块化开发的需要对EggJS进行了大量扩展和定制。

所以建议依次阅读
