### ISSUE TITLE
没有交流群吗

### ISSUE THREAD

**Issue by lixiang71** [zhennann/cabloy#3]

**Comment by zhennann** [comment]
最近忙，有计划，未实施。可先加我微信。微信号：yangjian2025

**Comment by zhennann** [comment]
为何建立交流群事宜拖了这么久？
是因为CabloyJS的社区也是用CabloyJS来开发的，
此外CabloyJS的文档也是用CabloyJS来实现的

**Comment by zhennann** [comment]
## CabloyJS微信官方交流群

欢迎加入微信群，请参见：[](https://community.cabloy.com/zh-cn/articles/wechat-qrcode.html)
