### ISSUE TITLE
docker-compose problem

### ISSUE THREAD

**Issue by metininan28one** [zhennann/cabloy#30]
using [egg-born-template-cabloy@4.30.9](https://github.com/zhennann/cabloy/releases/tag/egg-born-template-cabloy%404.30.9)

I tried to run docker-compose , however cabloy is not starting up due to an error:

here is the error log:

Error: secret should be set
cabloy-egg-born-template-cabloy-4309-app-1    |     at module.exports (/opt/node/app/node_modules/koa-jwt2/lib/index.js:21:42)
cabloy-egg-born-template-cabloy-4309-app-1    |     at module.exports (/opt/node/app/packages/egg-born-backend/app/middleware/jwt.js:99:19)
cabloy-egg-born-template-cabloy-4309-app-1    |     at CustomAppWorkerLoader.loadMiddleware (/opt/node/app/node_modules/egg-core/lib/loader/mixin/middleware.js:75:12)
cabloy-egg-born-template-cabloy-4309-app-1    |     at CustomAppWorkerLoader.load (/opt/node/app/node_modules/@zhennann/egg/lib/loader/app_worker_loader.js:39:10)
cabloy-egg-born-template-cabloy-4309-app-1    |     at CustomAppWorkerLoader.load (/opt/node/app/packages/egg-born-backend/lib/load/app.js:14:11)
cabloy-egg-born-template-cabloy-4309-app-1    |     at new Application (/opt/node/app/node_modules/@zhennann/egg/lib/application.js:66:19)
cabloy-egg-born-template-cabloy-4309-app-1    |     at new Application (/opt/node/app/packages/egg-born-backend/lib/framework.js:8:1)
cabloy-egg-born-template-cabloy-4309-app-1    |     at Object.<anonymous> (/opt/node/app/node_modules/egg-cluster/lib/app_worker.js:23:9)
cabloy-egg-born-template-cabloy-4309-app-1    |     at Module._compile (node:internal/modules/cjs/loader:1196:14)
cabloy-egg-born-template-cabloy-4309-app-1    |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1250:10)
cabloy-egg-born-template-cabloy-4309-app-1    |     at Module.load (node:internal/modules/cjs/loader:1074:32)
cabloy-egg-born-template-cabloy-4309-app-1    |     at Function.Module._load (node:internal/modules/cjs/loader:909:12)
cabloy-egg-born-template-cabloy-4309-app-1    |     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
cabloy-egg-born-template-cabloy-4309-app-1    |     at node:internal/main/run_main_module:22:47

**Comment by zhennann** [comment]
You should copy directory **_config** to **config**
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/24246985/228828815-7cdb0043-87fb-4a02-b7a4-0197a1feae2c.png">
