### ISSUE TITLE
windows 下 git bash 中运行 dev:front 域名不正确

### ISSUE THREAD

**Issue by ywzhaiqi** [zhennann/cabloy#40]
windows 下在 git bash 环境中运行 `npm run dev:front`，最后
```bash
> Listening at http://XXX:9092
```
其中 XXX 是 git bash 中环境变量 `HOSTNAME`，实际上是用户名。这个地址在浏览器中无法打开。

查看源码跟 `node_modules\@zhennann\build\lib\project\front\build\dev-server.js` 文件 34 行相关
```js
const hostname = process.env.HOSTNAME || context.config.dev.hostname;
```

我的临时解决方法：把 `dev:front` 改成
```
cross-env HOSTNAME=localhost egg-born-bin front-dev
```

**Comment by zhennann** [comment]
HOSTNAME作为主机名称，确实有可能是当前机器的用户名。在本地开发环境，一般不需要从process.env.HOSTNAME取值，直接从config.dev.hostname取值即可。
你可否提交PR，代码位于：https://github.com/zhennann/cabloy/blob/master/packages/build/lib/project/front/build/dev-server.js

**Comment by zhennann** [comment]
多谢反馈，已处理
