### ISSUE TITLE
Incorrect version dependency for egg-born-module-a-base-sync

### ISSUE THREAD

**Issue by hcp08gy** [zhennann/cabloy#51]
No matching version found for egg-born-module-a-base-sync@^5.0.0.

**Comment by zhennann** [comment]
5.0处于内测阶段，没有对外发布

**Comment by hcp08gy** [comment]
那该如何结局这个问题，跑其它分支吗？

**Comment by hcp08gy** [comment]
master分支上有包依赖这个egg-born-module-a-base-sync@^5.0.0.导致npm install失败，有什么解决方案吗？

**Comment by zhennann** [comment]
使用项目模式（https://cabloy.com/zh-cn/articles/guide-quick-start.html），不要直接clone源码仓库

**Comment by zhennann** [comment]
> 那该如何结局这个问题，跑其它分支吗？

The latest version of Cabloy 5.0 has been released, featuring a brand-new full-stack architecture compatible with Vibe Coding.
