### ISSUE TITLE
CMS 构建报错

### ISSUE THREAD

**Issue by zysdo** [zhennann/cabloy#6]
![image](https://user-images.githubusercontent.com/15885360/68292198-505cb900-00c6-11ea-9fb0-360721207a26.png)
huanj环境：win10

**Comment by zhennann** [comment]
[https://github.com/zhennann/egg-born-module-a-cms/commit/7f61d436fd7e427ee9673bbd2aa4685f52d4cb3e](https://github.com/zhennann/egg-born-module-a-cms/commit/7f61d436fd7e427ee9673bbd2aa4685f52d4cb3e)
