### ISSUE TITLE
建议CMS 增加 搜索引擎自动推送插件，  自动推送文章给 搜索引擎收录，通用插件功能

### ISSUE THREAD

**Issue by ehnote** [zhennann/cabloy#7]
例如： 百度的自动推送 和主动推送，  CMS 发布文章后，自动推送文章给百度收录

**Comment by zhennann** [comment]
[Cabloy商店-cms-pluginsubmit](https://store.cabloy.com/zh-cn/articles/cecb37b6f5a449ad9eae6fb2caf58934.html)
